version: '3'
services:
  web:
    build: .
    ports:
      - "5008:5000"
    volumes:
      - ./:/app
    networks:
      default:
        ipv4_address: 172.18.2.202
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.2.200/29
          gateway: 172.18.2.201
